SELECT * FROM users;
-- SELECT * FROM events;
-- SELECT * FROM items;
-- SELECT * FROM categories;
-- SELECT * FROM guest_details;
-- SELECT * FROM guest_items;
-- -- SELECT * FROM event_messages;
-- -- SELECT * FROM event_comments;
-- SELECT * FROM custom_recipes;
-- SELECT * FROM favorites;