
#LOGIN
POST http://localhost:3003/login
Content-Type: application/json

{
  "email": "georgina@email.com",
  "password": "1"
}

###

#SIGN UP
POST http://localhost:3003/signup
Content-Type: application/json

{ "first_name": "Test",
  "last_name": "Testing",
  "email": "test@email.com",
  "password": "1"
}

###

#SEARCH RECIPE
GET http://localhost:3003/recipes/search/
Content-Type: application/json

{
  "searchField": "pasta"
}

###

#ADD CUSTOM RECIPE
POST http://localhost:3003/recipes/add_recipe
Content-Type: application/json

{
  "user_id": 4, 
  "category_id": 2,
  "name": "Testing Lasagna",
  "ingredients": "Tomato sauce, pasta, salt, pepper, etc",
  "instructions": "Add tomato, add pasta, add salt, eat, be happy",
  "picture_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR022Bpb5JjwBLLlm1QEmeY5B78w2dhgcePlg&usqp=CAU"
}

### 

#ADD RECIPE TO FAVORITE

POST http://localhost:3003/favorite/add
Content-Type: application/json

{
  "user_id": 1,
  "recipe_id": 2
}