
#LOGIN
POST http://localhost:3003/login
Content-Type: application/json

{
  "email": "daniel@email.com",
  "password": "1"
}

###

#SIGN UP
POST http://localhost:3003/signup
Content-Type: application/json

{ "first_name": "Test",
  "last_name": "Testing",
  "email": "test@email.com",
  "password": "1"
}

###

#SEARCH RECIPE
GET http://localhost:3003/recipes/search/
Content-Type: application/json

{
  "searchField": "pasta"
}