const sampleData = {
  singleRecipes: [
    {
      vegetarian: false,
      vegan: false,
      glutenFree: false,
      dairyFree: false,
      veryHealthy: true,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      weightWatcherSmartPoints: 11,
      gaps: "no",
      lowFodmap: false,
      aggregateLikes: 2,
      spoonacularScore: 91.0,
      healthScore: 90.0,
      creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      license: "CC BY 3.0",
      sourceName: "Foodista",
      pricePerServing: 168.12,
      extendedIngredients: [
        {
          id: 20081,
          aisle: "Baking",
          image: "flour.png",
          consistency: "solid",
          name: "flour",
          original: "2 tablespoons Flour",
          originalString: "2 tablespoons Flour",
          originalName: "Flour",
          amount: 2.0,
          unit: "tablespoons",
          meta: [],
          metaInformation: [],
          measures: {
            us: {
              amount: 2.0,
              unitShort: "Tbsps",
              unitLong: "Tbsps",
            },
            metric: {
              amount: 2.0,
              unitShort: "Tbsps",
              unitLong: "Tbsps",
            },
          },
        },
        {
          id: 11291,
          aisle: "Produce",
          image: "spring-onions.jpg",
          consistency: "solid",
          name: "green onions",
          original: "cup Green Onions, chopped",
          originalString: "cup Green Onions, chopped",
          originalName: "Green Onions, chopped",
          amount: 1.0,
          unit: "cup",
          meta: ["chopped"],
          metaInformation: ["chopped"],
          measures: {
            us: {
              amount: 1.0,
              unitShort: "cup",
              unitLong: "cup",
            },
            metric: {
              amount: 236.588,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 1085,
          aisle: "Milk, Eggs, Other Dairy",
          image: "milk.jpg",
          consistency: "liquid",
          name: "non-fat milk",
          original: "1 1/4 cups Non-Fat Milk",
          originalString: "1 1/4 cups Non-Fat Milk",
          originalName: "Non-Fat Milk",
          amount: 1.25,
          unit: "cups",
          meta: [],
          metaInformation: [],
          measures: {
            us: {
              amount: 1.25,
              unitShort: "cups",
              unitLong: "cups",
            },
            metric: {
              amount: 295.735,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 4053,
          aisle: "Oil, Vinegar, Salad Dressing",
          image: "olive-oil.jpg",
          consistency: "liquid",
          name: "olive oil",
          original: "2 tablespoons Olive Oil",
          originalString: "2 tablespoons Olive Oil",
          originalName: "Olive Oil",
          amount: 2.0,
          unit: "tablespoons",
          meta: [],
          metaInformation: [],
          measures: {
            us: {
              amount: 2.0,
              unitShort: "Tbsps",
              unitLong: "Tbsps",
            },
            metric: {
              amount: 2.0,
              unitShort: "Tbsps",
              unitLong: "Tbsps",
            },
          },
        },
        {
          id: 11282,
          aisle: "Produce",
          image: "brown-onion.png",
          consistency: "solid",
          name: "onion",
          original: "2 tablespoons Onion, minced",
          originalString: "2 tablespoons Onion, minced",
          originalName: "Onion, minced",
          amount: 2.0,
          unit: "tablespoons",
          meta: ["minced"],
          metaInformation: ["minced"],
          measures: {
            us: {
              amount: 2.0,
              unitShort: "Tbsps",
              unitLong: "Tbsps",
            },
            metric: {
              amount: 2.0,
              unitShort: "Tbsps",
              unitLong: "Tbsps",
            },
          },
        },
        {
          id: 1033,
          aisle: "Cheese",
          image: "parmesan.jpg",
          consistency: "solid",
          name: "parmesan cheese",
          original: "1/4 cup Parmesan Cheese, grated",
          originalString: "1/4 cup Parmesan Cheese, grated",
          originalName: "Parmesan Cheese, grated",
          amount: 0.25,
          unit: "cup",
          meta: ["grated"],
          metaInformation: ["grated"],
          measures: {
            us: {
              amount: 0.25,
              unitShort: "cups",
              unitLong: "cups",
            },
            metric: {
              amount: 59.147,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 11297,
          aisle: "Produce;Spices and Seasonings",
          image: "parsley.jpg",
          consistency: "solid",
          name: "parsley",
          original: "cup Fresh Parsley or Basil, chopped",
          originalString: "cup Fresh Parsley or Basil, chopped",
          originalName: "Fresh Parsley or Basil, chopped",
          amount: 1.0,
          unit: "cup",
          meta: ["fresh", "chopped"],
          metaInformation: ["fresh", "chopped"],
          measures: {
            us: {
              amount: 1.0,
              unitShort: "cup",
              unitLong: "cup",
            },
            metric: {
              amount: 236.588,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 20420,
          aisle: "Pasta and Rice",
          image: "fusilli.jpg",
          consistency: "solid",
          name: "pasta",
          original: "8 ounces Tubular Pasta",
          originalString: "8 ounces Tubular Pasta",
          originalName: "Tubular Pasta",
          amount: 8.0,
          unit: "ounces",
          meta: [],
          metaInformation: [],
          measures: {
            us: {
              amount: 8.0,
              unitShort: "oz",
              unitLong: "ounces",
            },
            metric: {
              amount: 226.796,
              unitShort: "g",
              unitLong: "grams",
            },
          },
        },
        {
          id: 11304,
          aisle: "Produce",
          image: "peas.jpg",
          consistency: "solid",
          name: "peas",
          original: "1 cup Frozen Peas, thawed",
          originalString: "1 cup Frozen Peas, thawed",
          originalName: "Frozen Peas, thawed",
          amount: 1.0,
          unit: "cup",
          meta: ["frozen", "thawed"],
          metaInformation: ["frozen", "thawed"],
          measures: {
            us: {
              amount: 1.0,
              unitShort: "cup",
              unitLong: "cup",
            },
            metric: {
              amount: 236.588,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 6168,
          aisle: "Condiments",
          image: "hot-sauce-or-tabasco.png",
          consistency: "liquid",
          name: "pepper sauce",
          original: "1 dsh Hot Pepper Sauce",
          originalString: "1 dsh Hot Pepper Sauce",
          originalName: "dsh Hot Pepper Sauce",
          amount: 1.0,
          unit: "",
          meta: ["hot"],
          metaInformation: ["hot"],
          measures: {
            us: {
              amount: 1.0,
              unitShort: "",
              unitLong: "",
            },
            metric: {
              amount: 1.0,
              unitShort: "",
              unitLong: "",
            },
          },
        },
        {
          id: 15121,
          aisle: "Canned and Jarred",
          image: "canned-tuna.png",
          consistency: "solid",
          name: "water-packed tuna",
          original: "6 1/2 ounces Can Water-Packed Tuna, drained",
          originalString: "6 1/2 ounces Can Water-Packed Tuna, drained",
          originalName: "Water-Packed Tuna, drained",
          amount: 6.5,
          unit: "ounces",
          meta: ["drained"],
          metaInformation: ["drained"],
          measures: {
            us: {
              amount: 6.5,
              unitShort: "oz",
              unitLong: "ounces",
            },
            metric: {
              amount: 184.272,
              unitShort: "g",
              unitLong: "grams",
            },
          },
        },
      ],
      id: 654959,
      title: "Pasta With Tuna",
      readyInMinutes: 45,
      servings: 4,
      sourceUrl: "http://www.foodista.com/recipe/K6QWSKQM/pasta-with-tuna",
      image: "https://spoonacular.com/recipeImages/654959-556x370.jpg",
      imageType: "jpg",
      summary:
        'Pasta With Tuna might be just the main course you are searching for. One serving contains <b>421 calories</b>, <b>24g of protein</b>, and <b>10g of fat</b>. For <b>$1.68 per serving</b>, this recipe <b>covers 28%</b> of your daily requirements of vitamins and minerals. 1 person were impressed by this recipe. Head to the store and pick up flour, onion, peas, and a few other things to make it today. It is a good option if you\'re following a <b>pescatarian</b> diet. All things considered, we decided this recipe <b>deserves a spoonacular score of 92%</b>. This score is excellent. Try <a href="https://spoonacular.com/recipes/pasta-and-tuna-salad-ensalada-de-pasta-y-atn-226303">Pastan and Tuna Salad (Ensalada de Pasta y Atún)</a>, <a href="https://spoonacular.com/recipes/tuna-pasta-565100">Tuna Pasta</a>, and <a href="https://spoonacular.com/recipes/tuna-pasta-89136">Tuna Pasta</a> for similar recipes.',
      cuisines: [],
      dishTypes: ["lunch", "main course", "main dish", "dinner"],
      diets: ["pescatarian"],
      occasions: [],
      winePairing: {
        pairedWines: [],
        pairingText:
          "No one wine will suit every pasta dish. Pasta in a tomato-based sauce will usually work well with a medium-bodied red, such as a montepulciano or chianti. Pasta with seafood or pesto will fare better with a light-bodied white, such as a pinot grigio. Cheese-heavy pasta can pair well with red or white - you might try a sangiovese wine for hard cheeses and a chardonnay for soft cheeses. We may be able to make a better recommendation if you ask again with a specific pasta dish.",
        productMatches: [],
      },
      instructions:
        "<ol><li>Cook pasta in a large pot of boiling water until al dente. Drain and return to warm pot. Put olive oil in saucepan and add onion. Saute until transparent. Stir in flour and cook for a few seconds and then whisk in milk. Stir constantly until this thickens. Add peas, tuna (shredded into chunks,) parsley, green onions, cheese and hot pepper sauce. Pour over pasta and stir gently to mix. Serve at once.</li></ol>",
      analyzedInstructions: [
        {
          name: "",
          steps: [
            {
              number: 1,
              step:
                "Cook pasta in a large pot of boiling water until al dente.",
              ingredients: [
                {
                  id: 20420,
                  name: "pasta",
                  localizedName: "pasta",
                  image: "fusilli.jpg",
                },
                {
                  id: 14412,
                  name: "water",
                  localizedName: "water",
                  image: "water.png",
                },
              ],
              equipment: [
                {
                  id: 404752,
                  name: "pot",
                  localizedName: "pot",
                  image: "stock-pot.jpg",
                },
              ],
            },
            {
              number: 2,
              step:
                "Drain and return to warm pot. Put olive oil in saucepan and add onion.",
              ingredients: [
                {
                  id: 4053,
                  name: "olive oil",
                  localizedName: "olive oil",
                  image: "olive-oil.jpg",
                },
                {
                  id: 11282,
                  name: "onion",
                  localizedName: "onion",
                  image: "brown-onion.png",
                },
              ],
              equipment: [
                {
                  id: 404669,
                  name: "sauce pan",
                  localizedName: "sauce pan",
                  image: "sauce-pan.jpg",
                },
                {
                  id: 404752,
                  name: "pot",
                  localizedName: "pot",
                  image: "stock-pot.jpg",
                },
              ],
            },
            {
              number: 3,
              step:
                "Saute until transparent. Stir in flour and cook for a few seconds and then whisk in milk. Stir constantly until this thickens.",
              ingredients: [
                {
                  id: 20081,
                  name: "all purpose flour",
                  localizedName: "all purpose flour",
                  image: "flour.png",
                },
                {
                  id: 1077,
                  name: "milk",
                  localizedName: "milk",
                  image: "milk.png",
                },
              ],
              equipment: [
                {
                  id: 404661,
                  name: "whisk",
                  localizedName: "whisk",
                  image: "whisk.png",
                },
              ],
            },
            {
              number: 4,
              step:
                "Add peas, tuna (shredded into chunks,) parsley, green onions, cheese and hot pepper sauce.",
              ingredients: [
                {
                  id: 6168,
                  name: "hot sauce",
                  localizedName: "hot sauce",
                  image: "hot-sauce-or-tabasco.png",
                },
                {
                  id: 11291,
                  name: "green onions",
                  localizedName: "green onions",
                  image: "spring-onions.jpg",
                },
                {
                  id: 11297,
                  name: "parsley",
                  localizedName: "parsley",
                  image: "parsley.jpg",
                },
                {
                  id: 1041009,
                  name: "cheese",
                  localizedName: "cheese",
                  image: "cheddar-cheese.png",
                },
                {
                  id: 11304,
                  name: "peas",
                  localizedName: "peas",
                  image: "peas.jpg",
                },
                {
                  id: 10015121,
                  name: "tuna",
                  localizedName: "tuna",
                  image: "canned-tuna.png",
                },
              ],
              equipment: [],
            },
            {
              number: 5,
              step: "Pour over pasta and stir gently to mix.",
              ingredients: [
                {
                  id: 20420,
                  name: "pasta",
                  localizedName: "pasta",
                  image: "fusilli.jpg",
                },
              ],
              equipment: [],
            },
            {
              number: 6,
              step: "Serve at once.",
              ingredients: [],
              equipment: [],
            },
          ],
        },
      ],
      originalId: null,
      spoonacularSourceUrl: "https://spoonacular.com/pasta-with-tuna-654959",
    },
    {
      vegetarian: false,
      vegan: false,
      glutenFree: false,
      dairyFree: false,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      weightWatcherSmartPoints: 28,
      gaps: "no",
      lowFodmap: false,
      aggregateLikes: 1,
      spoonacularScore: 72.0,
      healthScore: 30.0,
      creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      license: "CC BY 3.0",
      sourceName: "Foodista",
      pricePerServing: 245.44,
      extendedIngredients: [
        {
          id: 1041009,
          aisle: "Cheese",
          image: "cheddar-cheese.png",
          consistency: "solid",
          name: "cheese",
          original: "1/2 cup Parmesean Cheese, grated",
          originalString: "1/2 cup Parmesean Cheese, grated",
          originalName: "Parmesean Cheese, grated",
          amount: 0.5,
          unit: "cup",
          meta: ["grated"],
          metaInformation: ["grated"],
          measures: {
            us: {
              amount: 0.5,
              unitShort: "cups",
              unitLong: "cups",
            },
            metric: {
              amount: 118.294,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 2018,
          aisle: "Spices and Seasonings",
          image: "fennel-seeds.jpg",
          consistency: "solid",
          name: "fennel seed",
          original: "1/4 teaspoon Fennel Seed, crushed",
          originalString: "1/4 teaspoon Fennel Seed, crushed",
          originalName: "Fennel Seed, crushed",
          amount: 0.25,
          unit: "teaspoon",
          meta: ["crushed"],
          metaInformation: ["crushed"],
          measures: {
            us: {
              amount: 0.25,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
            metric: {
              amount: 0.25,
              unitShort: "tsps",
              unitLong: "teaspoons",
            },
          },
        },
        {
          id: 2044,
          aisle: "Produce;Spices and Seasonings",
          image: "basil.jpg",
          consistency: "solid",
          name: "fresh basil",
          original: "1/4 cup Fresh Basil, chopped, or",
          originalString: "1/4 cup Fresh Basil, chopped, or",
          originalName: "Fresh Basil, chopped, or",
          amount: 0.25,
          unit: "cup",
          meta: ["fresh", "chopped"],
          metaInformation: ["fresh", "chopped"],
          measures: {
            us: {
              amount: 0.25,
              unitShort: "cups",
              unitLong: "cups",
            },
            metric: {
              amount: 59.147,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 11215,
          aisle: "Produce",
          image: "garlic.png",
          consistency: "solid",
          name: "garlic",
          original: "1 clove garlic, crushed",
          originalString: "1 clove garlic, crushed",
          originalName: "garlic, crushed",
          amount: 1.0,
          unit: "clove",
          meta: ["crushed"],
          metaInformation: ["crushed"],
          measures: {
            us: {
              amount: 1.0,
              unitShort: "clove",
              unitLong: "clove",
            },
            metric: {
              amount: 1.0,
              unitShort: "clove",
              unitLong: "clove",
            },
          },
        },
        {
          id: 11333,
          aisle: "Produce",
          image: "green-pepper.jpg",
          consistency: "solid",
          name: "green bell pepper",
          original: "1 cup Green Pepper, chopped",
          originalString: "1 cup Green Pepper, chopped",
          originalName: "Green Pepper, chopped",
          amount: 1.0,
          unit: "cup",
          meta: ["green", "chopped"],
          metaInformation: ["green", "chopped"],
          measures: {
            us: {
              amount: 1.0,
              unitShort: "cup",
              unitLong: "cup",
            },
            metric: {
              amount: 236.588,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 7036,
          aisle: "Meat",
          image: "raw-pork-sausage.png",
          consistency: "solid",
          name: "italian sausage",
          original: "1 pound Italian Sausage, casings",
          originalString: "1 pound Italian Sausage, casings",
          originalName: "Italian Sausage, casings",
          amount: 1.0,
          unit: "pound",
          meta: ["italian"],
          metaInformation: ["italian"],
          measures: {
            us: {
              amount: 1.0,
              unitShort: "lb",
              unitLong: "pound",
            },
            metric: {
              amount: 453.592,
              unitShort: "g",
              unitLong: "grams",
            },
          },
        },
        {
          id: 4053,
          aisle: "Oil, Vinegar, Salad Dressing",
          image: "olive-oil.jpg",
          consistency: "liquid",
          name: "olive oil",
          original: "2 tablespoons olive oil",
          originalString: "2 tablespoons olive oil",
          originalName: "olive oil",
          amount: 2.0,
          unit: "tablespoons",
          meta: [],
          metaInformation: [],
          measures: {
            us: {
              amount: 2.0,
              unitShort: "Tbsps",
              unitLong: "Tbsps",
            },
            metric: {
              amount: 2.0,
              unitShort: "Tbsps",
              unitLong: "Tbsps",
            },
          },
        },
        {
          id: 11282,
          aisle: "Produce",
          image: "brown-onion.png",
          consistency: "solid",
          name: "onion",
          original: "1 small onion",
          originalString: "1 small onion",
          originalName: "onion",
          amount: 1.0,
          unit: "small",
          meta: [],
          metaInformation: [],
          measures: {
            us: {
              amount: 1.0,
              unitShort: "small",
              unitLong: "small",
            },
            metric: {
              amount: 1.0,
              unitShort: "small",
              unitLong: "small",
            },
          },
        },
        {
          id: 11297,
          aisle: "Produce;Spices and Seasonings",
          image: "parsley.jpg",
          consistency: "solid",
          name: "parsley",
          original: "1/4 cup Italian Parsley, chopped",
          originalString: "1/4 cup Italian Parsley, chopped",
          originalName: "Italian Parsley, chopped",
          amount: 0.25,
          unit: "cup",
          meta: ["italian", "chopped"],
          metaInformation: ["italian", "chopped"],
          measures: {
            us: {
              amount: 0.25,
              unitShort: "cups",
              unitLong: "cups",
            },
            metric: {
              amount: 59.147,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 20420,
          aisle: "Pasta and Rice",
          image: "fusilli.jpg",
          consistency: "solid",
          name: "pasta",
          original: "12 ounces Pasta (your favourite)",
          originalString: "12 ounces Pasta (your favourite)",
          originalName: "Pasta (your favourite)",
          amount: 12.0,
          unit: "ounces",
          meta: ["(your favourite)"],
          metaInformation: ["(your favourite)"],
          measures: {
            us: {
              amount: 12.0,
              unitShort: "oz",
              unitLong: "ounces",
            },
            metric: {
              amount: 340.194,
              unitShort: "g",
              unitLong: "grams",
            },
          },
        },
        {
          id: 10011549,
          aisle: "Pasta and Rice",
          image: "tomato-sauce-or-pasta-sauce.jpg",
          consistency: "solid",
          name: "pasta sauce",
          original: "1 cup Tomato-Based Pasta Sauce",
          originalString: "1 cup Tomato-Based Pasta Sauce",
          originalName: "Tomato-Based Pasta Sauce",
          amount: 1.0,
          unit: "cup",
          meta: [],
          metaInformation: [],
          measures: {
            us: {
              amount: 1.0,
              unitShort: "cup",
              unitLong: "cup",
            },
            metric: {
              amount: 236.588,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 14102,
          aisle: "Alcoholic Beverages",
          image: "red-wine.jpg",
          consistency: "liquid",
          name: "red zinfandel",
          original: "1/2 cup Red Zinfandel",
          originalString: "1/2 cup Red Zinfandel",
          originalName: "Red Zinfandel",
          amount: 0.5,
          unit: "cup",
          meta: ["red"],
          metaInformation: ["red"],
          measures: {
            us: {
              amount: 0.5,
              unitShort: "cups",
              unitLong: "cups",
            },
            metric: {
              amount: 118.294,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: null,
          aisle: "?",
          image: null,
          consistency: null,
          name: "removed",
          original: "Removed",
          originalString: "Removed",
          originalName: "Removed",
          amount: 4.0,
          unit: "servings",
          meta: [],
          metaInformation: [],
          measures: {
            us: {
              amount: 4.0,
              unitShort: "servings",
              unitLong: "servings",
            },
            metric: {
              amount: 4.0,
              unitShort: "servings",
              unitLong: "servings",
            },
          },
        },
      ],
      id: 654928,
      title: "Pasta With Italian Sausage",
      readyInMinutes: 45,
      servings: 4,
      sourceUrl:
        "http://www.foodista.com/recipe/G8JXNCD8/pasta-with-italian-sausage",
      image: "https://spoonacular.com/recipeImages/654928-556x370.jpg",
      imageType: "jpg",
      summary:
        'The recipe Pasta With Italian Sausage could satisfy your Mediterranean craving in about <b>45 minutes</b>. This recipe serves 4 and costs $2.33 per serving. Watching your figure? This dairy free recipe has <b>832 calories</b>, <b>29g of protein</b>, and <b>44g of fat</b> per serving. This recipe is liked by 1 foodies and cooks. If you have parmesean cheese, basil, sausage, and a few other ingredients on hand, you can make it. To use up the onion you could follow this main course with the <a href="https://spoonacular.com/recipes/candy-corn-cupcakes-63881">Candy Corn Cupcakes</a> as a dessert. Not a lot of people really liked this main course. All things considered, we decided this recipe <b>deserves a spoonacular score of 74%</b>. This score is good. Try <a href="https://spoonacular.com/recipes/italian-sausage-and-pasta-557995">Italian Sausage and Pasta</a>, <a href="https://spoonacular.com/recipes/italian-sausage-pasta-pot-215729">Italian sausage & pasta pot</a>, and <a href="https://spoonacular.com/recipes/italian-sausage-pasta-272903">Italian Sausage Pasta</a> for similar recipes.',
      cuisines: ["Mediterranean", "Italian", "European"],
      dishTypes: ["lunch", "main course", "main dish", "dinner"],
      diets: [],
      occasions: [],
      winePairing: {},
      instructions:
        "<ol><li>Crumble sausage into a large skillet. Cook over medium heat, stirring often, until meat is well browned. Drain and set aside. In same skillet, cook onion, pepper, garlic, basil and fennel in 1 tb olive oil over medium heat, stirring often to scrape up browned bits from the bottom of pan. Cook until onion is translucent, about 5 minutes.</li><li>Add sausage, pasta sauce, and wine. Bring to a boil. Reduce heat and simmer 5 minutes. While sauce is cooking, in a large pot of boiling water cook pasta until al dente. Drain well.</li><li>On a large warm serving platter, combine parsley and 1 tb olive oil & fresh basil. Add pasta and toss to mix. Pour sauce over pasta. Sprinkle with Parmesean cheese.</li></ol>",
      analyzedInstructions: [
        {
          name: "",
          steps: [
            {
              number: 1,
              step:
                "Crumble sausage into a large skillet. Cook over medium heat, stirring often, until meat is well browned.",
              ingredients: [
                {
                  id: 1017063,
                  name: "sausage",
                  localizedName: "sausage",
                  image: "raw-pork-sausage.png",
                },
                {
                  id: 1065062,
                  name: "meat",
                  localizedName: "meat",
                  image: "whole-chicken.jpg",
                },
              ],
              equipment: [
                {
                  id: 404645,
                  name: "frying pan",
                  localizedName: "frying pan",
                  image: "pan.png",
                },
              ],
            },
            {
              number: 2,
              step:
                "Drain and set aside. In same skillet, cook onion, pepper, garlic, basil and fennel in 1 tb olive oil over medium heat, stirring often to scrape up browned bits from the bottom of pan. Cook until onion is translucent, about 5 minutes.",
              ingredients: [
                {
                  id: 4053,
                  name: "olive oil",
                  localizedName: "olive oil",
                  image: "olive-oil.jpg",
                },
                {
                  id: 11957,
                  name: "fennel",
                  localizedName: "fennel",
                  image: "fennel.png",
                },
                {
                  id: 11215,
                  name: "garlic",
                  localizedName: "garlic",
                  image: "garlic.png",
                },
                {
                  id: 1002030,
                  name: "pepper",
                  localizedName: "pepper",
                  image: "pepper.jpg",
                },
                {
                  id: 2044,
                  name: "basil",
                  localizedName: "basil",
                  image: "basil.jpg",
                },
                {
                  id: 11282,
                  name: "onion",
                  localizedName: "onion",
                  image: "brown-onion.png",
                },
              ],
              equipment: [
                {
                  id: 404645,
                  name: "frying pan",
                  localizedName: "frying pan",
                  image: "pan.png",
                },
              ],
              length: {
                number: 5,
                unit: "minutes",
              },
            },
            {
              number: 3,
              step:
                "Add sausage, pasta sauce, and wine. Bring to a boil. Reduce heat and simmer 5 minutes. While sauce is cooking, in a large pot of boiling water cook pasta until al dente.",
              ingredients: [
                {
                  id: 10011549,
                  name: "pasta sauce",
                  localizedName: "pasta sauce",
                  image: "tomato-sauce-or-pasta-sauce.jpg",
                },
                {
                  id: 1017063,
                  name: "sausage",
                  localizedName: "sausage",
                  image: "raw-pork-sausage.png",
                },
                {
                  id: 20420,
                  name: "pasta",
                  localizedName: "pasta",
                  image: "fusilli.jpg",
                },
                {
                  id: 0,
                  name: "sauce",
                  localizedName: "sauce",
                  image: "",
                },
                {
                  id: 14412,
                  name: "water",
                  localizedName: "water",
                  image: "water.png",
                },
                {
                  id: 14084,
                  name: "wine",
                  localizedName: "wine",
                  image: "red-wine.jpg",
                },
              ],
              equipment: [
                {
                  id: 404752,
                  name: "pot",
                  localizedName: "pot",
                  image: "stock-pot.jpg",
                },
              ],
              length: {
                number: 5,
                unit: "minutes",
              },
            },
            {
              number: 4,
              step:
                "Drain well.On a large warm serving platter, combine parsley and 1 tb olive oil & fresh basil.",
              ingredients: [
                {
                  id: 2044,
                  name: "fresh basil",
                  localizedName: "fresh basil",
                  image: "fresh-basil.jpg",
                },
                {
                  id: 4053,
                  name: "olive oil",
                  localizedName: "olive oil",
                  image: "olive-oil.jpg",
                },
                {
                  id: 11297,
                  name: "parsley",
                  localizedName: "parsley",
                  image: "parsley.jpg",
                },
              ],
              equipment: [],
            },
            {
              number: 5,
              step: "Add pasta and toss to mix.",
              ingredients: [
                {
                  id: 20420,
                  name: "pasta",
                  localizedName: "pasta",
                  image: "fusilli.jpg",
                },
              ],
              equipment: [],
            },
            {
              number: 6,
              step: "Pour sauce over pasta.",
              ingredients: [
                {
                  id: 20420,
                  name: "pasta",
                  localizedName: "pasta",
                  image: "fusilli.jpg",
                },
                {
                  id: 0,
                  name: "sauce",
                  localizedName: "sauce",
                  image: "",
                },
              ],
              equipment: [],
            },
            {
              number: 7,
              step: "Sprinkle with Parmesean cheese.",
              ingredients: [
                {
                  id: 1041009,
                  name: "cheese",
                  localizedName: "cheese",
                  image: "cheddar-cheese.png",
                },
              ],
              equipment: [],
            },
          ],
        },
      ],
      originalId: null,
      spoonacularSourceUrl:
        "https://spoonacular.com/pasta-with-italian-sausage-654928",
    },
    {
      vegetarian: false,
      vegan: false,
      glutenFree: false,
      dairyFree: false,
      veryHealthy: false,
      cheap: false,
      veryPopular: false,
      sustainable: false,
      weightWatcherSmartPoints: 8,
      gaps: "no",
      lowFodmap: false,
      aggregateLikes: 3,
      spoonacularScore: 55.0,
      healthScore: 15.0,
      creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      license: "CC BY 3.0",
      sourceName: "Foodista",
      pricePerServing: 145.96,
      extendedIngredients: [
        {
          id: 4053,
          aisle: "Oil, Vinegar, Salad Dressing",
          image: "olive-oil.jpg",
          consistency: "liquid",
          name: "olive oil",
          original: "1/4 cup olive oil",
          originalString: "1/4 cup olive oil",
          originalName: "olive oil",
          amount: 0.25,
          unit: "cup",
          meta: [],
          metaInformation: [],
          measures: {
            us: {
              amount: 0.25,
              unitShort: "cups",
              unitLong: "cups",
            },
            metric: {
              amount: 59.147,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 5062,
          aisle: "Meat",
          image: "chicken-breasts.png",
          consistency: "solid",
          name: "chicken breasts",
          original: "1/2 pound boneless chicken breasts cut in ½ in strips",
          originalString:
            "1/2 pound boneless chicken breasts cut in ½ in strips",
          originalName: "boneless chicken breasts cut in ½ in strips",
          amount: 0.5,
          unit: "pound",
          meta: ["boneless", "cut in ½ in strips"],
          metaInformation: ["boneless", "cut in ½ in strips"],
          measures: {
            us: {
              amount: 0.5,
              unitShort: "lb",
              unitLong: "pounds",
            },
            metric: {
              amount: 226.796,
              unitShort: "g",
              unitLong: "grams",
            },
          },
        },
        {
          id: 1032009,
          aisle: "Spices and Seasonings",
          image: "red-pepper-flakes.jpg",
          consistency: "solid",
          name: "red pepper flakes",
          original: "1 pinch red pepper flakes",
          originalString: "1 pinch red pepper flakes",
          originalName: "red pepper flakes",
          amount: 1.0,
          unit: "pinch",
          meta: ["red"],
          metaInformation: ["red"],
          measures: {
            us: {
              amount: 1.0,
              unitShort: "pinch",
              unitLong: "pinch",
            },
            metric: {
              amount: 1.0,
              unitShort: "pinch",
              unitLong: "pinch",
            },
          },
        },
        {
          id: 10620421,
          aisle: "Pasta and Rice",
          image: "lasagna-noodles.jpg",
          consistency: "solid",
          name: "cooked lasagna noodles",
          original:
            "1/2 pound bow tie pasta or small lasagna noodles, (cooked)",
          originalString:
            "1/2 pound bow tie pasta or small lasagna noodles, (cooked)",
          originalName: "bow tie pasta or small lasagna noodles, (cooked)",
          amount: 0.5,
          unit: "pound",
          meta: ["cooked", "()"],
          metaInformation: ["cooked", "()"],
          measures: {
            us: {
              amount: 0.5,
              unitShort: "lb",
              unitLong: "pounds",
            },
            metric: {
              amount: 226.796,
              unitShort: "g",
              unitLong: "grams",
            },
          },
        },
        {
          id: 11215,
          aisle: "Produce",
          image: "garlic.png",
          consistency: "solid",
          name: "garlic cloves",
          original: "2 garlic cloves, minced",
          originalString: "2 garlic cloves, minced",
          originalName: "garlic cloves, minced",
          amount: 2.0,
          unit: "",
          meta: ["minced"],
          metaInformation: ["minced"],
          measures: {
            us: {
              amount: 2.0,
              unitShort: "",
              unitLong: "",
            },
            metric: {
              amount: 2.0,
              unitShort: "",
              unitLong: "",
            },
          },
        },
        {
          id: 10011090,
          aisle: "Produce",
          image: "broccoli.jpg",
          consistency: "solid",
          name: "broccoli florets",
          original: "1 1/2 cups broccoli florets",
          originalString: "1 1/2 cups broccoli florets",
          originalName: "broccoli florets",
          amount: 1.5,
          unit: "cups",
          meta: [],
          metaInformation: [],
          measures: {
            us: {
              amount: 1.5,
              unitShort: "cups",
              unitLong: "cups",
            },
            metric: {
              amount: 354.882,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 2003,
          aisle: "Spices and Seasonings",
          image: "basil.jpg",
          consistency: "solid",
          name: "dried basil leaves",
          original: "1 teaspoon dried basil leaves",
          originalString: "1 teaspoon dried basil leaves",
          originalName: "dried basil leaves",
          amount: 1.0,
          unit: "teaspoon",
          meta: ["dried"],
          metaInformation: ["dried"],
          measures: {
            us: {
              amount: 1.0,
              unitShort: "tsp",
              unitLong: "teaspoon",
            },
            metric: {
              amount: 1.0,
              unitShort: "tsp",
              unitLong: "teaspoon",
            },
          },
        },
        {
          id: 14106,
          aisle: "Alcoholic Beverages",
          image: "white-wine.jpg",
          consistency: "liquid",
          name: "white wine",
          original: "1/4 cup white wine",
          originalString: "1/4 cup white wine",
          originalName: "white wine",
          amount: 0.25,
          unit: "cup",
          meta: ["white"],
          metaInformation: ["white"],
          measures: {
            us: {
              amount: 0.25,
              unitShort: "cups",
              unitLong: "cups",
            },
            metric: {
              amount: 59.147,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 6194,
          aisle: "Canned and Jarred",
          image: "chicken-broth.png",
          consistency: "liquid",
          name: "chicken broth",
          original: "3/4 cup chicken broth",
          originalString: "3/4 cup chicken broth",
          originalName: "chicken broth",
          amount: 0.75,
          unit: "cup",
          meta: [],
          metaInformation: [],
          measures: {
            us: {
              amount: 0.75,
              unitShort: "cups",
              unitLong: "cups",
            },
            metric: {
              amount: 177.441,
              unitShort: "ml",
              unitLong: "milliliters",
            },
          },
        },
        {
          id: 1033,
          aisle: "Cheese",
          image: "parmesan.jpg",
          consistency: "solid",
          name: "parmesan cheese",
          original: "Grated parmesan cheese",
          originalString: "Grated parmesan cheese",
          originalName: "Grated parmesan cheese",
          amount: 1.0,
          unit: "serving",
          meta: ["grated"],
          metaInformation: ["grated"],
          measures: {
            us: {
              amount: 1.0,
              unitShort: "serving",
              unitLong: "serving",
            },
            metric: {
              amount: 1.0,
              unitShort: "serving",
              unitLong: "serving",
            },
          },
        },
      ],
      id: 654901,
      title: "Pasta With Chicken and Broccoli",
      readyInMinutes: 45,
      servings: 4,
      sourceUrl:
        "https://www.foodista.com/recipe/Y5X6DRHT/pasta-with-chicken-and-broccoli",
      image: "https://spoonacular.com/recipeImages/654901-556x370.jpg",
      imageType: "jpg",
      summary:
        'Pasta With Chicken and Broccoli might be a good recipe to expand your main course repertoire. This recipe makes 4 servings with <b>332 calories</b>, <b>19g of protein</b>, and <b>18g of fat</b> each. For <b>$1.46 per serving</b>, this recipe <b>covers 16%</b> of your daily requirements of vitamins and minerals. 3 people found this recipe to be flavorful and satisfying. A mixture of wine, parmesan cheese, basil leaves, and a handful of other ingredients are all it takes to make this recipe so yummy. It is brought to you by Foodista. From preparation to the plate, this recipe takes approximately <b>approximately 45 minutes</b>. Taking all factors into account, this recipe <b>earns a spoonacular score of 55%</b>, which is solid. Similar recipes are <a href="https://spoonacular.com/recipes/pasta-house-pasta-con-broccoli-this-is-an-alfredo-based-sauce-that-combines-pasta-fresh-mushrooms-and-fresh-broccoli-601199">Pasta House Pasta con Broccoli – This is an Alfredo based sauce that combines pasta, fresh mushrooms, and fresh broccoli</a>, <a href="https://spoonacular.com/recipes/broccoli-and-pasta-with-chicken-479320">Broccoli and Pasta with Chicken</a>, and <a href="https://spoonacular.com/recipes/pasta-with-chicken-and-broccoli-110475">Pasta With Chicken and Broccoli</a>.',
      cuisines: [],
      dishTypes: ["side dish", "lunch", "main course", "main dish", "dinner"],
      diets: [],
      occasions: [],
      winePairing: {
        pairedWines: [],
        pairingText:
          "No one wine will suit every pasta dish. Pasta in a tomato-based sauce will usually work well with a medium-bodied red, such as a montepulciano or chianti. Pasta with seafood or pesto will fare better with a light-bodied white, such as a pinot grigio. Cheese-heavy pasta can pair well with red or white - you might try a sangiovese wine for hard cheeses and a chardonnay for soft cheeses. We may be able to make a better recommendation if you ask again with a specific pasta dish.",
        productMatches: [],
      },
      instructions:
        "In a large skillet, heat oil over medium heat. Sautee garlic for about one minute, stirring constantly. DO NOT BURN.\nAdd the chicken and cook until well done. Add the broccoli and cook until crisp but tender. Add basil; red pepper; salt and pepper to taste; wine and chicken broth. cook for about 5 minutes.\nAdd the cooked and drained pasta to the skillet and toss to combine.\nHeat for 1 to 2 minutes Serve.\nTop with grated Parmesan cheese if desired.",
      analyzedInstructions: [
        {
          name: "",
          steps: [
            {
              number: 1,
              step: "In a large skillet, heat oil over medium heat.",
              ingredients: [
                {
                  id: 4582,
                  name: "cooking oil",
                  localizedName: "cooking oil",
                  image: "vegetable-oil.jpg",
                },
              ],
              equipment: [
                {
                  id: 404645,
                  name: "frying pan",
                  localizedName: "frying pan",
                  image: "pan.png",
                },
              ],
            },
            {
              number: 2,
              step:
                "Sautee garlic for about one minute, stirring constantly. DO NOT BURN.",
              ingredients: [
                {
                  id: 11215,
                  name: "garlic",
                  localizedName: "garlic",
                  image: "garlic.png",
                },
              ],
              equipment: [],
              length: {
                number: 1,
                unit: "minutes",
              },
            },
            {
              number: 3,
              step: "Add the chicken and cook until well done.",
              ingredients: [
                {
                  id: 5006,
                  name: "whole chicken",
                  localizedName: "whole chicken",
                  image: "whole-chicken.jpg",
                },
              ],
              equipment: [],
            },
            {
              number: 4,
              step: "Add the broccoli and cook until crisp but tender.",
              ingredients: [
                {
                  id: 11090,
                  name: "broccoli",
                  localizedName: "broccoli",
                  image: "broccoli.jpg",
                },
              ],
              equipment: [],
            },
            {
              number: 5,
              step:
                "Add basil; red pepper; salt and pepper to taste; wine and chicken broth. cook for about 5 minutes.",
              ingredients: [
                {
                  id: 1102047,
                  name: "salt and pepper",
                  localizedName: "salt and pepper",
                  image: "salt-and-pepper.jpg",
                },
                {
                  id: 6194,
                  name: "chicken broth",
                  localizedName: "chicken broth",
                  image: "chicken-broth.png",
                },
                {
                  id: 11821,
                  name: "red pepper",
                  localizedName: "red pepper",
                  image: "red-pepper.jpg",
                },
                {
                  id: 2044,
                  name: "basil",
                  localizedName: "basil",
                  image: "basil.jpg",
                },
                {
                  id: 14084,
                  name: "wine",
                  localizedName: "wine",
                  image: "red-wine.jpg",
                },
              ],
              equipment: [],
              length: {
                number: 5,
                unit: "minutes",
              },
            },
            {
              number: 6,
              step:
                "Add the cooked and drained pasta to the skillet and toss to combine.",
              ingredients: [
                {
                  id: 20420,
                  name: "pasta",
                  localizedName: "pasta",
                  image: "fusilli.jpg",
                },
              ],
              equipment: [
                {
                  id: 404645,
                  name: "frying pan",
                  localizedName: "frying pan",
                  image: "pan.png",
                },
              ],
            },
            {
              number: 7,
              step: "Heat for 1 to 2 minutes",
              ingredients: [],
              equipment: [],
            },
            {
              number: 8,
              step: "Serve.",
              ingredients: [],
              equipment: [],
            },
            {
              number: 9,
              step: "Top with grated Parmesan cheese if desired.",
              ingredients: [
                {
                  id: 1032,
                  name: "grated parmesan cheese",
                  localizedName: "grated parmesan cheese",
                  image: "parmesan.jpg",
                },
              ],
              equipment: [],
            },
          ],
        },
      ],
      originalId: null,
      spoonacularSourceUrl:
        "https://spoonacular.com/pasta-with-chicken-and-broccoli-654901",
    },
  ],
  recipeSearches: [
    {
      results: [
        {
          id: 654959,
          title: "Pasta With Tuna",
          image: "https://spoonacular.com/recipeImages/654959-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 511728,
          title: "Pasta Margherita",
          image: "https://spoonacular.com/recipeImages/511728-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 654812,
          title: "Pasta and Seafood",
          image: "https://spoonacular.com/recipeImages/654812-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 654857,
          title: "Pasta On The Border",
          image: "https://spoonacular.com/recipeImages/654857-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 654883,
          title: "Pasta Vegetable Soup",
          image: "https://spoonacular.com/recipeImages/654883-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 654928,
          title: "Pasta With Italian Sausage",
          image: "https://spoonacular.com/recipeImages/654928-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 654926,
          title: "Pasta With Gorgonzola Sauce",
          image: "https://spoonacular.com/recipeImages/654926-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 654944,
          title: "Pasta With Salmon Cream Sauce",
          image: "https://spoonacular.com/recipeImages/654944-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 654905,
          title: "Pasta With Chickpeas and Kale",
          image: "https://spoonacular.com/recipeImages/654905-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 654901,
          title: "Pasta With Chicken and Broccoli",
          image: "https://spoonacular.com/recipeImages/654901-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 654913,
          title: "Pasta With Chicken and Mushrooms",
          image: "https://spoonacular.com/recipeImages/654913-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 654953,
          title: "Pasta with Spicy Sausage & Rapini",
          image: "https://spoonacular.com/recipeImages/654953-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 654835,
          title: "Pasta e Fagioli (Pasta and Beans)",
          image: "https://spoonacular.com/recipeImages/654835-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 654935,
          title: "Pasta with Peas and Italian Sausage",
          image: "https://spoonacular.com/recipeImages/654935-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 654911,
          title: "Pasta With Cream Sauce and Mushrooms",
          image: "https://spoonacular.com/recipeImages/654911-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 654797,
          title: "Pasta A La Lydia (Halloween Inspired)",
          image: "https://spoonacular.com/recipeImages/654797-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 654887,
          title: "Pasta Shells With Ricotta Cheese Stuffing",
          image: "https://spoonacular.com/recipeImages/654887-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 686582,
          title: "Pasta casserole with zucchini and chicken",
          image: "https://spoonacular.com/recipeImages/686582-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 654939,
          title: "Pasta With Roasted Vegetables & Greek Olives",
          image: "https://spoonacular.com/recipeImages/654939-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 654936,
          title: "Pasta with Raw Tomato & Lemon Infused Olive Oil",
          image: "https://spoonacular.com/recipeImages/654936-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 654902,
          title: "Pasta with Butternut Squash, Sausage and Sage Pesto",
          image: "https://spoonacular.com/recipeImages/654902-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 654897,
          title: "Pasta With Butternut Parmesan Sauce @ Dw Magazine.Com",
          image: "https://spoonacular.com/recipeImages/654897-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 716429,
          title: "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs",
          image: "https://spoonacular.com/recipeImages/716429-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 663126,
          title: "Thai Pasta Salad",
          image: "https://spoonacular.com/recipeImages/663126-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 649717,
          title: "Lemon Pasta With Shrimp",
          image: "https://spoonacular.com/recipeImages/649717-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 649721,
          title: "Lemon Pasta With Salmon",
          image: "https://spoonacular.com/recipeImages/649721-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 649718,
          title: "Lemon Pasta Alfredo (Vegan)",
          image: "https://spoonacular.com/recipeImages/649718-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 655575,
          title: "Penne Pasta with Broccoli and Cheese",
          image: "https://spoonacular.com/recipeImages/655575-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 655582,
          title: "Penne Pasta With Chicken And Mushrooms",
          image: "https://spoonacular.com/recipeImages/655582-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 637670,
          title: "Cheesy Pasta in a Pot",
          image: "https://spoonacular.com/recipeImages/637670-312x231.jpg",
          imageType: "jpg",
        },
      ],
      offset: 0,
      number: 30,
      totalResults: 210,
    },
    {
      results: [
        {
          id: 649395,
          title: "Lean Shepherd's Pie",
          image: "https://spoonacular.com/recipeImages/649395-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 1095880,
          title: "Easy Shepherd’s Pie",
          image: "https://spoonacular.com/recipeImages/1095880-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 642091,
          title: "Easy Shepherd's Pie (Beef And/or Lamb Combo)",
          image: "https://spoonacular.com/recipeImages/642091-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 636096,
          title: "Bridget Jones's Shepherd's Pie",
          image: "https://spoonacular.com/recipeImages/636096-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 664680,
          title: "Vegetarian Mushroom Shepherd's Pie",
          image: "https://spoonacular.com/recipeImages/664680-312x231.jpg",
          imageType: "jpg",
        },
      ],
      offset: 0,
      number: 30,
      totalResults: 5,
    },
    {
      results: [
        {
          id: 642539,
          title: "Falafel Burger",
          image: "https://spoonacular.com/recipeImages/642539-312x231.png",
          imageType: "png",
        },
        {
          id: 631814,
          title: "$50,000 Burger",
          image: "https://spoonacular.com/recipeImages/631814-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 663050,
          title: "Tex-Mex Burger",
          image: "https://spoonacular.com/recipeImages/663050-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 622825,
          title: "Tortilla Burger Loco Vaca",
          image: "https://spoonacular.com/recipeImages/622825-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 663357,
          title: "The Unagi Burger",
          image: "https://spoonacular.com/recipeImages/663357-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 651190,
          title: "Masala-Tofu Burger",
          image: "https://spoonacular.com/recipeImages/651190-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 663252,
          title: "The Blarney Burger",
          image: "https://spoonacular.com/recipeImages/663252-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 650181,
          title: "Little Italy Burger",
          image: "https://spoonacular.com/recipeImages/650181-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 663209,
          title: "The Benedict Burger",
          image: "https://spoonacular.com/recipeImages/663209-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 637631,
          title: "Cheesy Bacon Burger with Spicy Chipotle Aiolo Sauce",
          image: "https://spoonacular.com/recipeImages/637631-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 638771,
          title: "Chipotle-Salsa Burger",
          image: "https://spoonacular.com/recipeImages/638771-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 657243,
          title: "Pumpkin Almond Burger Patties",
          image: "https://spoonacular.com/recipeImages/657243-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 650377,
          title: "Low Carb Brunch Burger",
          image: "https://spoonacular.com/recipeImages/650377-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 780000,
          title: "Chicken Avocado Burger (Whole 30, PALEO, & Simple Fit Forty)",
          image: "https://spoonacular.com/recipeImages/780000-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 632342,
          title: "An American Beef Burger",
          image: "https://spoonacular.com/recipeImages/632342-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 649141,
          title: "La Bella Italian Turkey Burger",
          image: "https://spoonacular.com/recipeImages/649141-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 775621,
          title: "Gorgonzola & Grilled Peach Burger",
          image: "https://spoonacular.com/recipeImages/775621-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 635345,
          title: "Blue Cheese and Mushroom Turkey Burger",
          image: "https://spoonacular.com/recipeImages/635345-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 801377,
          title: "Chicken Parmesan Patty- Eat As A Burger OR On Pasta",
          image: "https://spoonacular.com/recipeImages/801377-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 664011,
          title: "Turkey Burgers",
          image: "https://spoonacular.com/recipeImages/664011-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 642540,
          title: "Falafel Burgers",
          image: "https://spoonacular.com/recipeImages/642540-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 648303,
          title: "Itty Bitty Burgers",
          image: "https://spoonacular.com/recipeImages/648303-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 635350,
          title: "Blue Cheese Burgers",
          image: "https://spoonacular.com/recipeImages/635350-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 642695,
          title: "Feta Stuffed Burgers",
          image: "https://spoonacular.com/recipeImages/642695-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 649940,
          title: "Lentil Veggie Burgers",
          image: "https://spoonacular.com/recipeImages/649940-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 650235,
          title: "Loaded Turkey Burgers",
          image: "https://spoonacular.com/recipeImages/650235-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 991010,
          title: "Chicken Ranch Burgers",
          image: "https://spoonacular.com/recipeImages/991010-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 649182,
          title: "Lamb and Bacon Burgers",
          image: "https://spoonacular.com/recipeImages/649182-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 632300,
          title: "Amazing Chicken Burgers",
          image: "https://spoonacular.com/recipeImages/632300-312x231.jpg",
          imageType: "jpg",
        },
        {
          id: 1096267,
          title: "Turkey Burgers with Slaw",
          image: "https://spoonacular.com/recipeImages/1096267-312x231.jpg",
          imageType: "jpg",
        },
      ],
      offset: 0,
      number: 30,
      totalResults: 53,
    },
  ],
};
